### ISSUE TITLE
license: use URI instead of snail-mail

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/cookiecutter-invenio-module#108]
As discussed with @ThiefMaster on Mattermost, Invenio copyright/license headers use still the old snail-mail address (=Boston) instead of pointing to license URL that https://www.gnu.org/licenses/gpl-faq.html examples now also recommends. We should switch to the modern version (and then amend existing sources on some rainy day...).

**Comment by lnielsen** [comment]
The official guide for GPLv2 still displays the address: https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html

As you mention the FAQ does show an example with the URL but that's under ["What legal issues come up if I use GPL-incompatible libraries with GPL software? "](https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs)

Perhaps it's better to just update the license text to GPLv3 (which should be possible without asking everyone given the current ones says GPLv2 or any later version).
