### ISSUE TITLE
Change the shebang to use bash

### ISSUE THREAD

**Issue by switowski** [inveniosoftware/cookiecutter-invenio-module#114]
As pointed out by @ntarocco in https://github.com/inveniosoftware/invenio-search/pull/110, we should use `#!/usr/bin/env bash` instead of `#!/usr/bin/env sh` for shebang notation (and here is why: https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang).
So the `{{ cookiecutter.project_shortname }}/run-tests.sh` template should be updated accordingly.

**Comment by slint** [comment]
Closed via #141.
