### ISSUE TITLE
Use pytest-invenio/selenium for exampleapp testing

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-module#126]
Currently the ``exampleapp`` is being tested via shell commands. This makes it hard to write maintainable test code, and also to debug failed tests in the CI system due to lack of output.

If instead, we switch to use pytest-invenio with selenium, we should be able to simply write normal E2E tests with pytest-invenio and selenium.

**Comment by Galixxon** [comment]
I'll give it a try!

**Comment by lnielsen** [comment]
I'm closing this one, as we have decided to [remove the example apps](https://github.com/inveniosoftware/rfcs/blob/master/framework/0021-example-apps-removal.md)
