### ISSUE TITLE
Lxml breaking when used inside uWSGI

### ISSUE THREAD

**Issue by Glignos** [inveniosoftware/cookiecutter-invenio-module#127]
We have pinpointed that in the latest versions of Lxml there has been introduced a breaking issue when it is used with uWSGI.
A quick fix is pinning the version to `lxml = ">=3.5.0,<4.2.6"` in the pipfile to keep it from upgrading beyond 4.2.6 where it seems the issue was introduced.

The error is : `ImportError: Interpreter change detected - this module can only be loaded into one interpreter per process.` when uWSGI is trying to mount invenio_app.wsgi_rest:application on /api.

**Comment by lnielsen** [comment]
Do you have links to any associated issues in lxml repository?

**Comment by Glignos** [comment]
There doesn't seem to be any.

**Comment by Glignos** [comment]
Reopened issue in appropriate repository https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/133 .
