### ISSUE TITLE
Deprecated flask_babelex import in views.py and ext.py

### ISSUE THREAD

**Issue by karkraeg** [inveniosoftware/cookiecutter-invenio-module#150]
Hi, in https://github.com/inveniosoftware/cookiecutter-invenio-module/issues/133 you purged the deprecated install requirement for `flask_babelex`. But the import in [views.py](https://github.com/inveniosoftware/cookiecutter-invenio-module/blob/master/%7B%7B%20cookiecutter.project_shortname%20%7D%7D/%7B%7B%20cookiecutter.package_name%20%7D%7D/views.py#L8) and [ext.py](https://github.com/inveniosoftware/cookiecutter-invenio-module/blob/master/%7B%7B%20cookiecutter.project_shortname%20%7D%7D/%7B%7B%20cookiecutter.package_name%20%7D%7D/ext.py#L4) are still wrong. We will open a PR for this :+1:

**Comment by chriz-uniba** [comment]
Looks related to: https://github.com/inveniosoftware/invenio-i18n/issues/88
