### ISSUE TITLE
cookiecutter: missing templates

### ISSUE THREAD

**Issue by jacenkow** [inveniosoftware/cookiecutter-invenio-module#36]
After installing an ```invenio cookiecutter``` module via ```pip install .```, I am not able to run ```examples/app.py``` since the templates are not installed, thus ```Jinja``` is raising ```jinja2.exceptions.TemplateNotFound```.

```bash
Grzegorz ∆ check-manifest -u
lists of files in version control and sdist do not match!
missing from sdist:
  AUTHORS.rst
  CHANGES.rst
  CONTRIBUTING.rst
  INSTALL.rst
  LICENSE
  RELEASE-NOTES.rst
  babel.ini
  beard_server/templates
  beard_server/templates/beard_server
  beard_server/templates/beard_server/base.html
  beard_server/templates/beard_server/index.html
  (...)
```

**Comment by jirikuncar** [comment]
@jacenkow did you add all newly generated file to your git repo (`git add -A`) before running `check-manifest -u`?

**Comment by jacenkow** [comment]
@jirikuncar yeah, I was following the steps from ```MANIFEST.in``` file.

**Comment by lnielsen** [comment]
How does your manifest looks like?

**Comment by kaplun** [comment]
@lnielsen isn't the manifest what is being generated by the cookiecutter, i.e.:
```
# TODO: Generate this manifest file by running the following commands:
#
#  git init
#  git add -A
#  pip install -e .[all]
#  check-manifest -u

# Check manifest will not automatically add these two files:
include .dockerignore
include .editorconfig
include .tx/config
recursive-include invenio_fungenerator *.po
recursive-include invenio_fungenerator *.mo
```

So it is currently not explicitly listing the templates. BTW it referes to `two files` but there are more.

**Comment by jirikuncar** [comment]
Generated MANIFEST.in clearly states:

```text
# TODO: Generate this manifest file by running the following commands:
#
#  git init
#  git add -A
#  pip install -e .[all]
#  check-manifest -u
```

so one **has** to run these commands manually.

--
`s/two files/these files/` :wink:

**Comment by kaplun** [comment]
OK. So that means that, after having just bootstrapped a module with `cookiecutter`, one still needs to do the above lines, before being able to `pip install` it and run it, correct?

**Comment by jirikuncar** [comment]
One have to fix **all** places marked as TODO.

**Comment by lnielsen** [comment]
@kaplun TODOs have to be fixed (e.g also ``setup.py`` needs minor fixes) - or if you want to use transfix you also need to extra stuff.....fact is you have to read the output, and remove stuff you don't need.
